name = menotics_landscaper
title = Menotics Landscaper Drone
description = A flying drone that moves in a 50-block radius, placing blocks and planting trees to automatically build a random biome-specific landscape.
author = ronrob-lu
release = 1.0.0
optional_depends = default
